name: deploy

on:
  push:
    branches:
      - master

jobs: 
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@master
      # 如果主题是使用git submodule添加的，必须要！否则构建会失败，但hugo不会报错，只会waring
      - name: Update theme
        run: git submodule update --init --recursive
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.91.2'
          # extended: true
      - name: Build
        run: hugo --minify
      - name: Deploy to Server
        uses: easingthemes/ssh-deploy@main
        env:
            SSH_PRIVATE_KEY: ${{ secrets.TOKEN }} 
            ARGS: "-avzr --delete" 
            SOURCE: "public/" 
            REMOTE_HOST: ${{ secrets.HOST }}  
            REMOTE_USER: ${{ secrets.USER }} 
            TARGET: ${{ secrets.TARGET }} 